name: Auto Format

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

jobs:

  clang-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install clang-format
      run: sudo apt-get install clang-format

    - name: Run clang-format
      run: |
        # Check if any file is not correctly formatted
        # You can add specific file extensions or paths you want to format, e.g., '*.cpp', '*.h'
        clang-format -i $(find . -name '*.cpp' -o -name '*.hpp' -o -name '*.h' -o -name '*.c')

    - name: Check for uncommitted changes
      id: format_check
      run: |
        # Check if clang-format introduced any changes
        if [[ `git status --porcelain` ]]; then
          echo "Files were not properly formatted. The changes will be pushed to branch main."
          echo "format_status=fail" >> $GITHUB_OUTPUT
        else
          echo "All files are properly formatted."
          echo "format_status=pass" >> $GITHUB_OUTPUT
        fi

    - name: Commit and push formatted changes
      if : ${{ steps.format_check.outputs.format_status == 'fail' }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add .
        git commit -m "[skip ci] Auto-format code with clang-format"
        git push

